language: en

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: KerasPolicy
    epochs: 100
    batch_size: 50
  - name: MappingPolicy
  - name: AugmentedMemoizationPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.2
    ambiguity_threshold: 0.1
    core_threshold: 0.2
    fallback_action_name: "action_default_fallback"
  - name: FormPolicy